(function () {
  'use strict';
  var cfg=window.GG_STANDALONE_QUIZ||{}, local=location.hostname==='localhost'||location.hostname==='127.0.0.1'||location.protocol==='file:';
  var api=String(local?cfg.localApiUrl:cfg.apiUrl||'').replace(/\/$/,''), LOG='[GG Quiz]';
  var learnerId=localStorage.getItem('gg_quiz_learner_id')||(crypto.randomUUID?crypto.randomUUID():'learner-'+Date.now());
  localStorage.setItem('gg_quiz_learner_id',learnerId);
  var form=document.getElementById('quizForm'),list=document.getElementById('questionList'),status=document.getElementById('quizStatus'),submit=document.getElementById('quizSubmit'),note=document.getElementById('answerNote'),progress=document.getElementById('quizProgress'),count=document.getElementById('quizCount'),result=document.getElementById('quizResult'),attemptMeta=document.getElementById('quizAttemptMeta');
  var questions=[],attempt=null;
  function debug(message,detail){if(detail===undefined)console.info(LOG,message);else console.info(LOG,message,detail);}
  function escapeHtml(value){var d=document.createElement('div');d.textContent=value;return d.innerHTML;}
  function token(){return localStorage.getItem('gg_access_token');}
  function headers(){var h={'Content-Type':'application/json'};if(token())h.Authorization='Bearer '+token();return h;}
  function selectedCount(){return form.querySelectorAll('input[type=radio]:checked').length;}
  function apiPost(path,body){debug('API request',{path:path,learnerId:learnerId.slice(0,8)+'…'});return fetch(api+path,{method:'POST',headers:headers(),body:JSON.stringify(body)}).then(function(response){debug('API response',{path:path,status:response.status,ok:response.ok});return response.json().then(function(data){if(!response.ok)throw new Error(data.error||'Request failed');return data;});});}
  function updateProgress(){var n=selectedCount();progress.style.width=(questions.length?n/questions.length*100:0)+'%';count.textContent=n+' of '+questions.length+' answered';note.textContent=n===questions.length?'Ready to submit':'Answer every question before submitting';submit.disabled=!questions.length||n!==questions.length;}
  function renderAttempt(data){attempt=data;questions=data.questions||[];result.className='result';result.innerHTML='';document.getElementById('quizTitle').textContent=data.title||'Knowledge Check';attemptMeta.textContent='Attempt '+data.attemptNumber+' of 4 · '+data.questionCount+' questions · '+data.retakesRemaining+' retakes remaining';list.innerHTML=questions.map(function(q,i){var headingId='quizQuestion'+(i+1);return '<section class="question" role="group" aria-labelledby="'+headingId+'"><h2 class="question-title" id="'+headingId+'"><span class="q-number">QUESTION '+(i+1)+'</span>'+escapeHtml(q.text)+'</h2><div class="options">'+q.options.map(function(option,oi){return '<label class="option"><span class="option-letter">'+String.fromCharCode(65+oi)+'</span><input type="radio" name="'+escapeHtml(q.id)+'" value="'+escapeHtml(option.id)+'"><span>'+escapeHtml(option.text)+'</span></label>';}).join('')+'</div></section>';}).join('');status.hidden=true;list.hidden=false;document.getElementById('quizActions').hidden=false;updateProgress();debug(data.resumed?'Resumed active attempt':'Started seeded attempt',{attemptId:data.attemptId,attemptNumber:data.attemptNumber,questionCount:questions.length});}
  function showTerminal(data){status.hidden=true;list.hidden=true;document.getElementById('quizActions').hidden=true;count.textContent='Attempt history complete';result.className='result show'+(data.passed?'':' fail');result.innerHTML='<h2>'+(data.passed?'Quiz already completed':'No retakes remaining')+'</h2><p>'+(data.passed?'Your passing result is recorded.':'This test session has used the initial attempt and all three retakes.')+'</p>';}
  function showError(message,error){console.error(LOG,message,error||'');status.hidden=false;status.className='status error';status.textContent=message;}
  function startAttempt(){if(!api)return showError('Quiz API is not configured.');status.hidden=false;status.className='status';status.textContent='Preparing your seeded question set…';list.hidden=true;document.getElementById('quizActions').hidden=true;apiPost('/attempts/start',{quizSeed:cfg.seed,learnerId:learnerId}).then(function(data){if(data.complete)showTerminal(data);else renderAttempt(data);}).catch(function(error){showError(error.message,error);});}
  function missedMarkup(missed){if(!missed||!missed.length)return'';return '<div class="missed"><div class="missed-title">Questions answered incorrectly</div><ol>'+missed.map(function(item){return '<li><span>Question '+item.number+'</span>'+escapeHtml(item.text)+'</li>';}).join('')+'</ol><p>The correct answers are intentionally not shown.</p></div>';}
  form.addEventListener('change',updateProgress);
  form.addEventListener('submit',function(event){event.preventDefault();submit.disabled=true;submit.textContent='Grading…';var answers={};form.querySelectorAll('input[type=radio]:checked').forEach(function(el){answers[el.name]=el.value;});debug('Submitting seeded attempt',{attemptId:attempt.attemptId,answerCount:Object.keys(answers).length});apiPost('/attempts/submit',{attemptId:attempt.attemptId,answers:answers}).then(function(data){debug('Attempt graded',{score:data.score,total:data.total,percent:data.percent,passed:data.passed,retakesRemaining:data.retakesRemaining});result.className='result show'+(data.passed?'':' fail');result.innerHTML='<p class="result-score">'+data.score+' / '+data.total+'</p><h2>'+(data.passed?'Quiz passed':'Attempt not passed')+'</h2><p>'+data.percent+'% · '+data.passMark+'% required · '+data.retakesRemaining+' retakes remaining</p>'+missedMarkup(data.missed)+(data.canRetake?'<button type="button" class="secondary" id="quizRetake">Start retake</button>':'');result.scrollIntoView({behavior:'smooth',block:'center'});list.hidden=true;document.getElementById('quizActions').hidden=true;if(data.passed)setTrainingState(true);var retake=document.getElementById('quizRetake');if(retake)retake.onclick=startAttempt;}).catch(function(error){showError(error.message,error);}).finally(function(){submit.textContent='Submit answers';updateProgress();});});
  function setTrainingState(completed){document.dispatchEvent(new CustomEvent('gg:quizteststate',{detail:{itemId:'5-1',completed:completed}}));if(window.GGTraining&&window.GGTraining.setTestProgress)return window.GGTraining.setTestProgress('5-1',completed);if(completed&&window.GGTraining&&window.GGTraining.markPartComplete)return window.GGTraining.markPartComplete('5-1');return Promise.resolve(false);}
  document.getElementById('testMarkComplete').onclick=function(){setTrainingState(true).then(function(){debug('Testing control: marked complete');});};
  document.getElementById('testMarkIncomplete').onclick=function(){setTrainingState(false).then(function(){debug('Testing control: marked incomplete');});};
  document.getElementById('testReset').onclick=function(){if(!confirm('Reset all quiz attempts and mark Module 5 incomplete for this test learner?'))return;apiPost('/test/reset',{quizSeed:cfg.seed,learnerId:learnerId}).then(function(){return setTrainingState(false);}).then(function(){form.reset();result.className='result';startAttempt();debug('Testing control: quiz and progress reset');}).catch(function(error){showError(error.message,error);});};
  debug('Initializing seeded quiz',{apiUrl:api,quizSeed:cfg.seed,authenticated:!!token(),learnerId:learnerId.slice(0,8)+'…'});startAttempt();
}());
